//
//  GrocerySection.swift
//  Manyam_GroceryApp
//
//  Created by Manyam,Siva Rama Krishna on 4/5/22.
//

import Foundation

struct Grocery {
var section = ""
var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let groceryitem1 = Grocery(section:"Food",items_Array:[GroceryItem(itemName:"MasalaDosa",itemImage:"masaladosa",itemInfo:"A crispy, rice-batter crepe encases a spicy mix of mashed potato, which is then dipped in coconut chutney, pickles, tomato-and-lentil-based sauces and other condiments. It's a fantastic breakfast food that'll keep you going till lunch, when you'll probably come back for another."), GroceryItem(itemName: "Hummus", itemImage: "hummus", itemInfo: "This humble Middle Eastern spread, made with chickpeas, garlic, lemon juice and tahini has become a fridge staple all around the world. This tangy treat tastes good as a dip, with breads, with meats, with vegetables, beans or -- hear us out -- on a Marmite rice cake."), GroceryItem(itemName: "Butter garlic crab", itemImage: "buttergarliccrab", itemInfo: "This one claims no roots in Chinese, Continental or Indian cuisines. It comes from Butter Land, an imaginary best foods paradise balanced on the premise that anything tastes great with melted butter. This delicious, simple dish is made by drowning a large crab in a gallon of butter-garlic sauce, which seeps into every nook and cranny and coats every inch of flesh. The sea gods of Butter Land are benevolent carnivores and this, their gift to the world, is their signature dish."), GroceryItem(itemName: "Corn", itemImage: "corn", itemInfo: "God probably created corn just to have an excuse to invent melted butter. There's something about biting down on a cob of corn -- it's a delicate enough operation to require concentration but primal enough to make you feel like the caveman you always wanted to be. Great food is caveman food."), GroceryItem(itemName: "Sushi", itemImage: "sushi", itemInfo: "When Japan wants to build something right, it builds it really right. Brand giants such as Toyota, Nintendo, Sony, Nikon and Yamaha may have been created by people fueled by nothing more complicated than raw fish and rice, but it's how the fish and rice is put together that makes this a global first-date favorite. The Japanese don't live practically forever for no reason -- they want to keep eating this stuff.")] )

let groceryitem2 = Grocery( section: "Toys", items_Array: [GroceryItem(itemName: "Hasbro’s Star Wars", itemImage: "toy1", itemInfo: "Hasbro’s Star Wars Collection: The Child Animatronic Edition with sounds and motorized sequences! He may look like “Baby Yoda,” but this lovable creature is called The Child -- and now you can become his protector with this animatronic toy from Star Wars."), GroceryItem(itemName: "Story Time Chess", itemImage: "toy2", itemInfo: "Story Time Chess is a board game that teaches chess to young children using silly stories, vibrant illustrations, custom chess pieces, and a unique chess board. The stories and supporting materials communicate the rules of chess to children ages 3 and up in a way that makes learning chess simple and fun. "), GroceryItem(itemName: "Comic Remastered", itemImage: "toy3", itemInfo: "In 1992, the very first Spawn comic book hit the shelves setting a sales record for an independent comic book. A few years later, in 1995, the first Spawn action figure was released to critical acclaim and helped usher in a whole new way of giving you detail and ‘art’ to your action figures."), GroceryItem(itemName: "The Razor Crest™", itemImage: "toy4", itemInfo: "Kids can role-play as heroic warrior The Mandalorian and play out action-packed Star Wars: The Mandalorian scenes with this detailed, LEGO brick model of The Razor Crest (75292) starship"), GroceryItem(itemName: "Pokémon", itemImage: "toy5", itemInfo: "This set includes everything two players need to battle. Trade, collect, or duel with these cards. Choose between beloved monsters like Charizard or Pikachu to lead your team in a fight against another trainer. Make Ash Ketchum proud and battle with the best!")] )

let groceryitem3 = Grocery( section: "Books", items_Array: [GroceryItem(itemName: "A Tale of Two Cities", itemImage: "book1", itemInfo: "A Tale of Two Cities is an 1859 historical novel by Charles Dickens, set in London and Paris before and during the French Revolution. The novel tells the story of the French Doctor Manette, his 18-year-long imprisonment in the Bastille in Paris, and his release to live in London with his daughter Lucie whom he had never met. "), GroceryItem(itemName: "The Little Prince", itemImage: "book2", itemInfo: "The Little Prince (French: Le Petit Prince, pronounced [lə p(ə)ti pʁɛ̃s]) is a novella by French aristocrat, writer, and military aviator Antoine de Saint-Exupéry. It was first published in English and French in the United States by Reynal & Hitchcock in April 1943. "), GroceryItem(itemName: "Harry Potter and the Philosopher's Stone", itemImage: "book3", itemInfo: "Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry."), GroceryItem(itemName: "And Then There Were None", itemImage: "book4", itemInfo: "And Then There Were None is a mystery novel by the English writer Agatha Christie, described by her as the most difficult of her books to write.[2] It was first published in the United Kingdom by the Collins Crime Club on 6 November 1939, as Ten Little Niggers."), GroceryItem(itemName: "Dream of the Red Chamber", itemImage: "book5", itemInfo: "Dream of the Red Chamber (Honglou Meng) or The Story of the Stone (Shitou Ji) is a novel composed by Cao Xueqin in the middle of the 18th century. One of the Four Great Classical Novels of Chinese literature, it is known for its psychological scope, and its observation of the world view, aesthetics, life-styles, and social relations of 18th-century China.")] )

let groceryitem4 = Grocery( section: "Beverages", items_Array: [GroceryItem(itemName: "Water", itemImage: "b1", itemInfo: "Water is the most popular drink in the world. This is such a simple beverage, and yet no one can survive without it. This is why people have invented different water treatment systems, to ensure everyone around the world can have clean and safe water to drink."), GroceryItem(itemName: "Tea", itemImage: "b2", itemInfo: "After water, tea is the most popular drink in the world. Tea is made by pouring hot water over cured tea leaves. This popular beverage can be enjoyed hot or cold, and can bring different health benefits. Tea plants mostly grow in Asia, but tea is enjoyed in many countries around the world."), GroceryItem(itemName: "Coffee", itemImage: "b3", itemInfo: "Coffee beans are produced in at least 70 countries around the world, and many people drink coffee several times a day. It is mostly enjoyed hot, but iced coffee is also very popular, especially in the summer. Just like tea leaves, coffee beans come from an evergreen shrub."), GroceryItem(itemName: "Orange juice", itemImage: "b4", itemInfo: "Orange juice is the most popular of all the fruit juices. Many people enjoy buying orange juice that is made from concentrate, but some prefer squeezing fresh oranges to make their own orange juice. This delicious beverage is a high source of vitamin C."), GroceryItem(itemName: "Beer", itemImage: "b5", itemInfo: "Beer is the most popular alcoholic beverage in the world, and it can be enjoyed for any occasion. This refreshing fermented beverage has probably been around since prehistoric times, and it is definitely here to stay as it is being consumed in every country around the world.")] )

let groceryitem5 = Grocery( section: "Clothing", items_Array: [GroceryItem(itemName: "Casual", itemImage: "c1", itemInfo: "Casual style is what you might wear on the weekend. Think jeans, comfortable T-shirts, and sneakers or flat boots. Both streetwear and sporty style might be considered types of casual styles, but casual style can also lean preppy or hip."), GroceryItem(itemName: "Streetwear", itemImage: "c2", itemInfo: "Streetwear is a casual fashion style that first became popular in the 1990s. It incorporates comfortable yet trendy clothing such as logo T-shirts and crop tops, hoodies, baggy pants, and expensive sneakers. Streetwear takes inspiration from both hip-hop and skater style, with the added element of intentional product scarcity."), GroceryItem(itemName: "Classic", itemImage: "c3", itemInfo: "Classic style is an umbrella term for a polished everyday style that incorporates elements of workwear, such as blazers, pencil skirts, and khakis. This more professional look is appropriate for the office and other settings where you want to look your best."), GroceryItem(itemName: "Sporty", itemImage: "c4", itemInfo: "Sporty style, also known as athleisure, takes elements of athletic wear, like leggings, bike shorts, and oversize sweatshirts, out of the gym and onto the streets."), GroceryItem(itemName: "Bohemian", itemImage: "c5", itemInfo: "Also known as “boho” or “boho chic,” bohemian style borrows from the 1960’s hippie aesthetic and festival culture. The style incorporates earth tones, natural fabrics and dyes, and prints and accessories from around the world. ")] )


let grocerys = [groceryitem1, groceryitem2, groceryitem3, groceryitem4, groceryitem5]
