//
//  GrocerySection.swift
//  OMTRI_GroceryApp
//
//  Created by Omtri,Homakesavadurgaprasad on 4/12/22.
//

import Foundation
struct Grocery {
var section = ""
var items_Array:[GroceryItem] = []
}

struct GroceryItem{
    var itemName = ""
    var itemImage = ""
    var itemInfo = ""
}

let groceryitem1 = Grocery(section:"Meat & Seafood",items_Array:[GroceryItem(itemName:"Anchovies",itemImage:"f1",itemInfo:"An anchovy is a small, common forage fish of the family Engraulidae. Most species are found in marine waters, but several will enter brackish water, and some in South America are restricted to fresh water"), GroceryItem(itemName: "Pomfrets", itemImage: "f2", itemInfo: "Pomfrets are perciform fishes belonging to the family Bramidae. The family currently includes 20 species across seven genera. Several species are important food sources for humans, especially Brama brama in South Asia."), GroceryItem(itemName: "Caviar", itemImage: "f3", itemInfo: "Caviar also known as caviare is a food consisting of salt-cured roe of the family Acipenseridae. Caviar is considered a delicacy and is eaten as a garnish or a spread."), GroceryItem(itemName: "Chicken", itemImage: "f4", itemInfo: "Chicken is the most common type of poultry in the world.Owing to the relative ease and low cost of raising chickens—in comparison to mammals such as cattle or hogs—chicken meat commonly called just,chicken, and chicken eggs have become prevalent in numerous cuisines. "),GroceryItem(itemName:"Anchovies",itemImage:"f1",itemInfo:"An anchovy is a small, common forage fish of the family Engraulidae. Most species are found in marine waters, but several will enter brackish water, and some in South America are restricted to fresh water")] )

let groceryitem2 = Grocery( section: "Pantry", items_Array: [GroceryItem(itemName: "Tomato sauce", itemImage: "p1", itemInfo: "A traditional marinara has tomatoes, garlic, and basil. Tomato sauce has more ingredients including onions, carrots, celery, and additional seasonings"), GroceryItem(itemName: "Rice", itemImage: "p2", itemInfo: "As a cereal grain, domesticated rice is the most widely consumed staple food for over half of the world's human population, especially in Asia and Africa. "), GroceryItem(itemName: "Sugar", itemImage: "p3", itemInfo: "White sugar is a refined form of sucrose. In the body, compound sugars are hydrolysed into simple sugars. Longer chains of monosaccharides"), GroceryItem(itemName: "Onion", itemImage: "p4", itemInfo: "The onion also known as the bulb onion or common onion, is a vegetable that is the most widely cultivated species of the genus Allium."),GroceryItem(itemName: "Onion", itemImage: "p4", itemInfo: "The onion also known as the bulb onion or common onion, is a vegetable that is the most widely cultivated species of the genus Allium.")] )


let groceryitem3 = Grocery( section: "Frozen", items_Array: [GroceryItem(itemName: "Icecream", itemImage: "fr1", itemInfo: "Ice cream is a sweetened frozen food typically eaten as a snack or dessert. It may be made from milk or cream and is flavoured with a sweetener "), GroceryItem(itemName: "Yogurt", itemImage: "fr2", itemInfo: "Yogurt also spelled yoghurt, yogourt or yoghourt, is a food produced by bacterial fermentation of milk. The bacteria used to make yogurt are known as yogurt cultures. "), GroceryItem(itemName: "Frozen Pizza", itemImage: "fr3", itemInfo: "Italian origin consisting of a usually round, flat base of leavened wheat-based dough topped with tomatoes, cheese, and often various other ingredients (such as anchovies, mushrooms, onions, olives, pineapple, meat, etc."), GroceryItem(itemName: "Shrimp and prawn", itemImage: "fr4", itemInfo: "Shrimp and prawn are types of seafood that are consumed worldwide. Although shrimp and prawns belong to different suborders of Decapoda, they are very similar in appearance and the terms are often used interchangeably in commercial farming and wild fisheries"),GroceryItem(itemName: "Shrimp and prawn", itemImage: "fr4", itemInfo: "Shrimp and prawn are types of seafood that are consumed worldwide. Although shrimp and prawns belong to different suborders of Decapoda, they are very similar in appearance and the terms are often used interchangeably in commercial farming and wild fisheries")] )

let groceryitem4 = Grocery( section: "Beverages", items_Array: [GroceryItem(itemName: "Pepsi", itemImage: "b1", itemInfo: "Pepsi is a carbonated soft drink manufactured by PepsiCo. Originally created and developed in 1893 by Caleb Bradham and introduced as Brad's Drink, it was renamed as Pepsi-Cola in 1898, and then shortened to Pepsi in 1961."), GroceryItem(itemName: "Sparkling drinks", itemImage: "b2", itemInfo: "Sparkling drinks or the so-called sodas contain carbonated drinks, a sweetener, and a natural or artificial flavoring. You can find these compounds in Coca-Cola Classic, Pepsi, Diet Coke, Mountain Dew, etc."), GroceryItem(itemName: "MockTails", itemImage: "b3", itemInfo: "A non-alcoholic mixed drink is a cocktail-style beverage made without alcoholic ingredients. Also called zero proof drinks, the non-alcoholic drink dates back to the earliest days of the cocktail age, appearing as Temperance drinks in the first American cocktail books, including Jerry Thomas's Bar-Tenders Guide."), GroceryItem(itemName: "Smoothie", itemImage: "b4", itemInfo: "A smoothie or smoothy is a drink made by puréeing fruits and/or vegetables in a blender. A smoothie often has a liquid base such as fruit juice, or dairy products such as milk, yogurt, ice cream or cottage cheese."),GroceryItem(itemName: "Smoothie", itemImage: "b4", itemInfo: "A smoothie or smoothy is a drink made by puréeing fruits and/or vegetables in a blender. A smoothie often has a liquid base such as fruit juice, or dairy products such as milk, yogurt, ice cream or cottage cheese.")] )

let groceryitem5 = Grocery( section: "Fresh Produce", items_Array: [GroceryItem(itemName: "Apple", itemImage: "fp1", itemInfo: "An apple is an edible fruit produced by an apple tree . Apple trees are cultivated worldwide and are the most widely gr"), GroceryItem(itemName: "Oranges", itemImage: "fp2", itemInfo: "Oranges are believed to be native to the tropical regions of Asia, especially the Malay Archipelago; along with other citrus species, they have been cultivated from remote ages."), GroceryItem(itemName: "Winter squash", itemImage: "fp3", itemInfo: "Winter squash is an annual fruit representing several squash species within the genus Cucurbita. It differs from summer squash in that it is harvested and eaten in the mature stage when the seeds within have matured fully and the skin has hardened into a tough rind."), GroceryItem(itemName: "Cabbage", itemImage: "fp4", itemInfo: "Cabbage  is an edible plant. It is a lot like broccoli, cauliflower or Brussels sprouts. Cabbage is eaten in many ways around the world. "),GroceryItem(itemName: "Cabbage", itemImage: "fp4", itemInfo: "Cabbage  is an edible plant. It is a lot like broccoli, cauliflower or Brussels sprouts. Cabbage is eaten in many ways around the world. ")] )


let grocerys = [groceryitem1, groceryitem2, groceryitem3, groceryitem4, groceryitem5]


